#!/bin/bash

echo updating...
sudo DEBIAN_FRONTEND=noninteractive apt update -y
echo UPDATED!

echo upgrade packages...
sudo DEBIAN_FRONTEND=noninteractive apt upgrade -y
echo PACKAGES UPGRADED!

# install mongo db 7.0.6

echo installing mongo db...
sudo apt-get install gnupg curl 

curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | \
   sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg \
   --dearmor

echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list

sudo apt-get update

sudo DEBIAN_FRONTEND=noninteractive apt-get install -y mongodb-org=7.0.6 mongodb-org-database=7.0.6 mongodb-org-server=7.0.6 mongodb-mongosh=2.2.4 mongodb-org-mongos=7.0.6 mongodb-org-tools=7.0.6

echo "mongodb-org hold" | sudo dpkg --set-selections
echo "mongodb-org-database hold" | sudo dpkg --set-selections
echo "mongodb-org-server hold" | sudo dpkg --set-selections
echo "mongodb-mongosh hold" | sudo dpkg --set-selections
echo "mongodb-org-mongos hold" | sudo dpkg --set-selections
echo "mongodb-org-tools hold" | sudo dpkg --set-selections

echo MONGO DB INSTALLED!

echo checking mongodb version...
mongod --version

echo starting mongo db...
sudo systemctl start mongod
echo MONGO DB STARTED!

# configure bind IP in mongo db config file , change it to 0.0.0.0

echo changing the bind IP to 0.0.0.0
sudo sed -i 's/^\(\s*\)bindIp: .*/\1bindIp: 0.0.0.0/' /etc/mongod.conf
# in network interfaces, change bind IP to 0.0.0.0

# restart mongo db
sudo systemctl restart mongod

# enable mongo db
sudo systemctl enable mongod

# make sure its running correctly
echo checking mongo db status
sudo systemctl status mongod
echo MONGO DB STATUS CHECKED!